dist: xenial
osx_image: xcode10.1
language: node_js
node_js: '8'
env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - YARN_GPG=no
  - secure: gaznh1apGpUtgSUg4S2x7OJSGK6pcAVpyaicYZUPTYrryGrutJkGpk/MeFGQlK1TAsWVnhMR8lAZgxC/ZPRmsied3Uef67N6LnH1jQcZUmw6pYeaSUkrn1lC8UCYaDkWQkhv0Hs7RT5KEwe/Nnd1L+m+E7w13C1a1cNIO5g4H9quVISD5tqeXNU7oWE9wTKrhXN0jDvE8K+wUUUojr6dgvjCEPB8Zs+8IKtgonD+991EA8ZIX9jXD5Yb0E6lzAsy3ZOvi1cv+b36/GKCzEhM8RiCPNWjJZb/6BUnzvbD38WfBnuhOh6ps2Wm3d+n7DHnfU4Uegg2bSpxymR0ojRfIs0qPkIRHYqIdDVANbXhan8Up9fWxVbNgpeSESqO0U/kG1Lme01rE5Cs0NW4l0dHUvD8taGkv2Cjha7nY0krxWawNKIgThkovbeREaugFCJbHdG0Nv+6Ng6xwqqhc7veUnM5T/qSofYeIlY1OzVq9X6NyZpBCjxMTAV9ksHqLbiMwZbKzFUK2BKJiX3mFG/xjMlsXjgK6gGJmGN6JNxI1N1rkbwFXbEnB7cvcVDYHErLm04OlkCohq/wnL2846lHm8d6zXhGGRDkxnuhT+vTydPuz8AfIjFx45UHhUrAqSI783zgkZN7ewXJ7E9qGZDeGTuHZLlfdBFgjfTt8mZ/DxM=
os:
- linux
- osx
- windows
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
  - "$HOME/.npm/_prebuilds"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
- export PATH=$HOME/.yarn/bin:$PATH
- node --version && yarn --version && python --version
- git clone --depth=50 --branch=master https://github.com/evolvedbinary/pebble-extension.git
  $TRAVIS_BUILD_DIR/../pebble-extension
install:
- pushd $TRAVIS_BUILD_DIR/../pebble-extension && yarn && yarn run sass && popd
- yarn
script: yarn build && yarn package
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
